import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/navbar/Navbar.js';
import { Footer } from '../components/footer/Footer.js';
import { Question } from '../components/question/Question.js';
import { useRef, useState } from 'react';
import { QuestionNew } from '../components/question/QuestionNew.js';

let myVar = 'test';

export default function Home() {

    let questionCallbackRef = useRef();

    let child = {};

    const [testValue, setTestValue] = useState("value")


    const _handleClick = () => {
        child.increment();
        // if (questionCallbackRef.current) {
        //     questionCallbackRef.current();
        // }
    }

    function yesClick() {
        setTestValue('This is the new value!!');
    }

    return (
        <div className={styles.wrapper}>

            <Head>
                <title>Sprint retro tombola</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar/>

            <div className={styles.main} onClick={_handleClick}>

               <QuestionNew myprop={testValue} ref={instance => { child = instance; }}/>

               <button onClick={yesClick}>UPDATE TEST MESSAGE</button>

                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/master/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </div>

            <Footer/>

        </div>
    )
}
